//
//  Artifact+ID+CustomDebugStringConvertible.swift
//  HoMM3SwiftUI
//
//  Created by Alexander Cyon on 2021-09-01.
//

import Foundation

public extension Artifact.ID {
    var debugDescription: String {
        switch self {
        case .spellBook: return "spellBook"
        case .spellScroll: return "spellScroll"
        case .grail: return "grail"
        case .catapult: return "catapult"
        case .ballista: return "ballista"
        case .ammoCart: return "ammoCart"
        case .firstAidTent: return "firstAidTent"
        case .centaurAxe: return "centaurAxe"
        case .blackshardOfTheDeadKnight: return "blackshardOfTheDeadKnight"
        case .greaterGnollsFlail: return "greaterGnollsFlail"
        case .ogresClubOfHavoc: return "ogresClubOfHavoc"
        case .swordOfHellfire: return "swordOfHellfire"
        case .titansGladius: return "titansGladius"
        case .shieldOfTheDwarvenLords: return "shieldOfTheDwarvenLords"
        case .shieldOfTheYawningDead: return "shieldOfTheYawningDead"
        case .bucklerOfTheGnollKing: return "bucklerOfTheGnollKing"
        case .targOfTheRampagingOgre: return "targOfTheRampagingOgre"
        case .shieldOfTheDamned: return "shieldOfTheDamned"
        case .sentinelsShield: return "sentinelsShield"
        case .helmOfTheAlabasterUnicorn: return "helmOfTheAlabasterUnicorn"
        case .skullHelmet: return "skullHelmet"
        case .helmOfChaos: return "helmOfChaos"
        case .crownOfTheSupremeMagi: return "crownOfTheSupremeMagi"
        case .hellstormHelmet: return "hellstormHelmet"
        case .thunderHelmet: return "thunderHelmet"
        case .breastplateOfPetrifiedWood: return "breastplateOfPetrifiedWood"
        case .ribCage: return "ribCage"
        case .scalesOfTheGreaterBasilisk: return "scalesOfTheGreaterBasilisk"
        case .tunicOfTheCyclopsKing: return "tunicOfTheCyclopsKing"
        case .breastplateOfBrimstone: return "breastplateOfBrimstone"
        case .titansCuirass: return "titansCuirass"
        case .armorOfWonder: return "armorOfWonder"
        case .sandalsOfTheSaint: return "sandalsOfTheSaint"
        case .celestialNecklaceOfBliss: return "celestialNecklaceOfBliss"
        case .lionsShieldOfCourage: return "lionsShieldOfCourage"
        case .swordOfJudgement: return "swordOfJudgement"
        case .helmOfHeavenlyEnlightenment: return "helmOfHeavenlyEnlightenment"
        case .quietEyeOfTheDragon: return "quietEyeOfTheDragon"
        case .redDragonFlameTongue: return "redDragonFlameTongue"
        case .dragonScaleShield: return "dragonScaleShield"
        case .dragonScaleArmor: return "dragonScaleArmor"
        case .dragonboneGreaves: return "dragonboneGreaves"
        case .dragonWingTabard: return "dragonWingTabard"
        case .necklaceOfDragonteeth: return "necklaceOfDragonteeth"
        case .crownOfDragontooth: return "crownOfDragontooth"
        case .stillEyeOfTheDragon: return "stillEyeOfTheDragon"
        case .cloverOfFortune: return "cloverOfFortune"
        case .cardsOfProphecy: return "cardsOfProphecy"
        case .ladybirdOfLuck: return "ladybirdOfLuck"
        case .badgeOfCourage: return "badgeOfCourage"
        case .crestOfValor: return "crestOfValor"
        case .glyphOfGallantry: return "glyphOfGallantry"
        case .speculum: return "speculum"
        case .spyglass: return "spyglass"
        case .amuletOfTheUndertaker: return "amuletOfTheUndertaker"
        case .vampiresCowl: return "vampiresCowl"
        case .deadMansBoots: return "deadMansBoots"
        case .garnitureOfInterference: return "garnitureOfInterference"
        case .surcoatOfCounterpoise: return "surcoatOfCounterpoise"
        case .bootsOfPolarity: return "bootsOfPolarity"
        case .bowOfElvenCherrywood: return "bowOfElvenCherrywood"
        case .bowstringOfTheUnicornsMane: return "bowstringOfTheUnicornsMane"
        case .angelFeatherArrows: return "angelFeatherArrows"
        case .birdOfPerception: return "birdOfPerception"
        case .stoicWatchman: return "stoicWatchman"
        case .emblemOfCognizance: return "emblemOfCognizance"
        case .statesmansMedal: return "statesmansMedal"
        case .diplomatsRing: return "diplomatsRing"
        case .ambassadorsSash: return "ambassadorsSash"
        case .ringOfTheWayfarer: return "ringOfTheWayfarer"
        case .equestriansGloves: return "equestriansGloves"
        case .necklaceOfOceanGuidance: return "necklaceOfOceanGuidance"
        case .angelWings: return "angelWings"
        case .charmOfMana: return "charmOfMana"
        case .talismanOfMana: return "talismanOfMana"
        case .mysticOrbOfMana: return "mysticOrbOfMana"
        case .collarOfConjuring: return "collarOfConjuring"
        case .ringOfConjuring: return "ringOfConjuring"
        case .capeOfConjuring: return "capeOfConjuring"
        case .orbOfTheFirmament: return "orbOfTheFirmament"
        case .orbOfSilt: return "orbOfSilt"
        case .orbOfTempestuousFire: return "orbOfTempestuousFire"
        case .orbOfDrivingRain: return "orbOfDrivingRain"
        case .recantersCloak: return "recantersCloak"
        case .spiritOfOppression: return "spiritOfOppression"
        case .hourglassOfTheEvilHour: return "hourglassOfTheEvilHour"
        case .tomeOfFireMagic: return "tomeOfFireMagic"
        case .tomeOfAirMagic: return "tomeOfAirMagic"
        case .tomeOfWaterMagic: return "tomeOfWaterMagic"
        case .tomeOfEarthMagic: return "tomeOfEarthMagic"
        case .bootsOfLevitation: return "bootsOfLevitation"
        case .goldenBow: return "goldenBow"
        case .sphereOfPermanence: return "sphereOfPermanence"
        case .orbOfVulnerability: return "orbOfVulnerability"
        case .ringOfVitality: return "ringOfVitality"
        case .ringOfLife: return "ringOfLife"
        case .vialOfLifeblood: return "vialOfLifeblood"
        case .necklaceOfSwiftness: return "necklaceOfSwiftness"
        case .bootsOfSpeed: return "bootsOfSpeed"
        case .capeOfVelocity: return "capeOfVelocity"
        case .pendantOfDispassion: return "pendantOfDispassion"
        case .pendantOfSecondSight: return "pendantOfSecondSight"
        case .pendantOfHoliness: return "pendantOfHoliness"
        case .pendantOfLife: return "pendantOfLife"
        case .pendantOfDeath: return "pendantOfDeath"
        case .pendantOfFreeWill: return "pendantOfFreeWill"
        case .pendantOfNegativity: return "pendantOfNegativity"
        case .pendantOfTotalRecall: return "pendantOfTotalRecall"
        case .pendantOfCourage: return "pendantOfCourage"
        case .everflowingCrystalCloak: return "everflowingCrystalCloak"
        case .ringOfInfiniteGems: return "ringOfInfiniteGems"
        case .everpouringVialOfMercury: return "everpouringVialOfMercury"
        case .inexhaustibleCartOfOre: return "inexhaustibleCartOfOre"
        case .eversmokingRingOfSulfur: return "eversmokingRingOfSulfur"
        case .inexhaustibleCartOfLumber: return "inexhaustibleCartOfLumber"
        case .endlessSackOfGold: return "endlessSackOfGold"
        case .endlessBagOfGold: return "endlessBagOfGold"
        case .endlessPurseOfGold: return "endlessPurseOfGold"
        case .legsOfLegion: return "legsOfLegion"
        case .loinsOfLegion: return "loinsOfLegion"
        case .torsoOfLegion: return "torsoOfLegion"
        case .armsOfLegion: return "armsOfLegion"
        case .headOfLegion: return "headOfLegion"
        case .seaCaptainsHat: return "seaCaptainsHat"
        case .spellbindersHat: return "spellbindersHat"
        case .shacklesOfWar: return "shacklesOfWar"
        case .orbOfInhibition: return "orbOfInhibition"
            
        // AB
        case .vialOfDragonBlood: return "vialOfDragonBlood"
        case .armageddonsBlade: return "armageddonsBlade"
            
        // SOD
        case .angelicAlliance: return "angelicAlliance"
        case .cloakOfTheUndeadKing: return "cloakOfTheUndeadKing"
        case .elixirOfLife: return "elixirOfLife"
        case .armorOfTheDamned: return "armorOfTheDamned"
        case .statueOfLegion: return "statueOfLegion"
        case .powerOfTheDragonFather: return "powerOfTheDragonFather"
        case .titansThunder: return "titansThunder"
        case .admiralHat: return "admiralHat"
        case .bowOfTheSharpshooter: return "bowOfTheSharpshooter"
        case .wizardWell: return "wizardWell"
        case .ringOfTheMagi: return "ringOfTheMagi"
        case .cornucopia: return "cornucopia"
            
        #if WOG
        case .magicWand: return "magicWand"
        case .goldTowerArrow: return "goldTowerArrow"
        case .monstersPower: return "monstersPower"
        case .highlightedSlot: return "highlightedSlot"
        case .artifactLock: return "artifactLock"
        case .axeOfSmashing: return "axeOfSmashing"
        case .mithrilMail: return "mithrilMail"
        case .swordOfSharpness: return "swordOfSharpness"
        case .helmOfImmortality: return "helmOfImmortality"
        case .pendantOfSorcery: return "pendantOfSorcery"
        case .bootsOfHaste: return "bootsOfHaste"
        case .bowOfSeeking: return "bowOfSeeking"
        case .dragonEyeRing: return "dragonEyeRing"
        case .hardenedShield: return "hardenedShield"
        case .slavasRingOfPower: return "slavasRingOfPower"
        case .warlordsBanner: return "warlordsBanner"
        case .crimsonShieldOfRetribution: return "crimsonShieldOfRetribution"
        case .barbarianLordsAxeOfFerocity: return "barbarianLordsAxeOfFerocity"
        case .dragonheart: return "dragonheart"
        case .gateKey: return "gateKey"
        case .blankHelmet: return "blankHelmet"
        case .blankSword: return "blankSword"
        case .blankShield: return "blankShield"
        case .blankHornedRing: return "blankHornedRing"
        case .blankGemmedRing: return "blankGemmedRing"
        case .blankNeckBroach: return "blankNeckBroach"
        case .blankArmor: return "blankArmor"
        case .blankSurcoat: return "blankSurcoat"
        case .blankBoots: return "blankBoots"
        case .blankHorn: return "blankHorn"
            
        #endif // WOG
        }
    }
}
