//
//  Creature+ID+CustomDebugStringConvertible.swift
//  HoMM3SwiftUI
//
//  Created by Alexander Cyon on 2021-09-07.
//

import Foundation

public extension Creature.ID {
    
    
    var debugDescription: String {
        name
    }
    
    var name: String {
        switch self {
        case .pikeman: return "pikeman"
        case .halberdier: return "halberdier"
        case .archer: return "archer"
        case .marksman: return "marksman"
        case .griffin: return "griffin"
        case .royalGriffin: return "royalGriffin"
        case .swordsman: return "swordsman"
        case .crusader: return "crusader"
        case .monk: return "monk"
        case .zealot: return "zealot"
        case .cavalier: return "cavalier"
        case .champion: return "champion"
        case .angel: return "angel"
        case .archangel: return "archangel"
        case .centaur: return "centaur"
        case .centaurCaptain: return "centaurCaptain"
        case .dwarf: return "dwarf"
        case .battleDwarf: return "battleDwarf"
        case .woodElf: return "woodElf"
        case .grandElf: return "grandElf"
        case .pegasus: return "pegasus"
        case .silverPegasus: return "silverPegasus"
        case .dendroidGuard: return "dendroidGuard"
        case .dendroidSoldier: return "dendroidSoldier"
        case .unicorn: return "unicorn"
        case .warUnicorn: return "warUnicorn"
        case .greenDragon: return "greenDragon"
        case .goldDragon: return "goldDragon"
        case .gremlin: return "gremlin"
        case .masterGremlin: return "masterGremlin"
        case .stoneGargoyle: return "stoneGargoyle"
        case .obsidianGargoyle: return "obsidianGargoyle"
        case .stoneGolem: return "stoneGolem"
        case .ironGolem: return "ironGolem"
        case .mage: return "mage"
        case .archMage: return "archMage"
        case .genie: return "genie"
        case .masterGenie: return "masterGenie"
        case .naga: return "naga"
        case .nagaQueen: return "nagaQueen"
        case .giant: return "giant"
        case .titan: return "titan"
        case .imp: return "imp"
        case .familiar: return "familiar"
        case .gog: return "gog"
        case .magog: return "magog"
        case .hellHound: return "hellHound"
        case .cerberus: return "cerberus"
        case .demon: return "demon"
        case .hornedDemon: return "hornedDemon"
        case .pitFiend: return "pitFiend"
        case .pitLord: return "pitLord"
        case .efreeti: return "efreeti"
        case .efreetSultan: return "efreetSultan"
        case .devil: return "devil"
        case .archDevil: return "archDevil"
        case .skeleton: return "skeleton"
        case .skeletonWarrior: return "skeletonWarrior"
        case .walkingDead: return "walkingDead"
        case .zombie: return "zombie"
        case .wight: return "wight"
        case .wraith: return "wraith"
        case .vampire: return "vampire"
        case .vampireLord: return "vampireLord"
        case .lich: return "lich"
        case .powerLich: return "powerLich"
        case .blackKnight: return "blackKnight"
        case .dreadKnight: return "dreadKnight"
        case .boneDragon: return "boneDragon"
        case .ghostDragon: return "ghostDragon"
        case .troglodyte: return "troglodyte"
        case .infernalTroglodyte: return "infernalTroglodyte"
        case .harpy: return "harpy"
        case .harpyHag: return "harpyHag"
        case .beholder: return "beholder"
        case .evilEye: return "evilEye"
        case .medusa: return "medusa"
        case .medusaQueen: return "medusaQueen"
        case .minotaur: return "minotaur"
        case .minotaurKing: return "minotaurKing"
        case .manticore: return "manticore"
        case .scorpicore: return "scorpicore"
        case .redDragon: return "redDragon"
        case .blackDragon: return "blackDragon"
        case .goblin: return "goblin"
        case .hobgoblin: return "hobgoblin"
        case .wolfRider: return "wolfRider"
        case .wolfRaider: return "wolfRaider"
        case .orc: return "orc"
        case .orcChieftain: return "orcChieftain"
        case .ogre: return "ogre"
        case .ogreMage: return "ogreMage"
        case .roc: return "roc"
        case .thunderbird: return "thunderbird"
        case .cyclops: return "cyclops"
        case .cyclopsKing: return "cyclopsKing"
        case .behemoth: return "behemoth"
        case .ancientBehemoth: return "ancientBehemoth"
        case .gnoll: return "gnoll"
        case .gnollMarauder: return "gnollMarauder"
        case .lizardman: return "lizardman"
        case .lizardWarrior: return "lizardWarrior"
        case .gorgon: return "gorgon"
        case .mightyGorgon: return "mightyGorgon"
        case .serpentFly: return "serpentFly"
        case .dragonFly: return "dragonFly"
        case .basilisk: return "basilisk"
        case .greaterBasilisk: return "greaterBasilisk"
        case .wyvern: return "wyvern"
        case .wyvernMonarch: return "wyvernMonarch"
        case .hydra: return "hydra"
        case .chaosHydra: return "chaosHydra"
        case .airElemental: return "airElemental"
        case .earthElemental: return "earthElemental"
        case .fireElemental: return "fireElemental"
        case .waterElemental: return "waterElemental"
        case .goldGolem: return "goldGolem"
        case .diamondGolem: return "diamondGolem"
        case .pixie: return "pixie"
        case .sprite: return "sprite"
        case .psychicElemental: return "psychicElemental"
        case .magicElemental: return "magicElemental"
        case .iceElemental: return "iceElemental"
        case .magmaElemental: return "magmaElemental"
        case .stormElemental: return "stormElemental"
        case .energyElemental: return "energyElemental"
        case .firebird: return "firebird"
        case .phoenix: return "phoenix"
        case .azureDragon: return "azureDragon"
        case .crystalDragon: return "crystalDragon"
        case .faerieDragon: return "faerieDragon"
        case .rustDragon: return "rustDragon"
        case .enchanter: return "enchanter"
        case .sharpshooter: return "sharpshooter"
        case .halfling: return "halfling"
        case .peasant: return "peasant"
        case .boar: return "boar"
        case .mummy: return "mummy"
        case .nomad: return "nomad"
        case .rogue: return "rogue"
        case .troll: return "troll"
        
        #if WOG
        case .supremeArchangel: return "supremeArchangel"
        case .diamondDragon: return "diamondDragon"
        case .lordOfThunder: return "lordOfThunder"
        case .antiChrist: return "antiChrist"
        case .bloodDragon: return "bloodDragon"
        case .darknessDragon: return "darknessDragon"
        case .ghostBehemoth: return "ghostBehemoth"
        case .hellHydra: return "hellHydra"
        case .sacredPhoenix: return "sacredPhoenix"
        case .ghost: return "ghost"
        case .emissaryofWar: return "emissaryofWar"
        case .emissaryofPeace: return "emissaryofPeace"
        case .emissaryofMana: return "emissaryofMana"
        case .emissaryofLore: return "emissaryofLore"
        case .fireMessenger: return "fireMessenger"
        case .earthMessenger: return "earthMessenger"
        case .airMessenger: return "airMessenger"
        case .waterMessenger: return "waterMessenger"
        case .gorynych: return "gorynych"
        case .warzealot: return "warzealot"
        case .arcticSharpshooter: return "arcticSharpshooter"
        case .lavaSharpshooter: return "lavaSharpshooter"
        case .nightmare: return "nightmare"
        case .santaGremlin: return "santaGremlin"
        case .sylvanCentaur: return "sylvanCentaur"
        case .sorceress: return "sorceress"
        case .werewolf: return "werewolf"
        case .hellSteed: return "hellSteed"
        case .dracolich: return "dracolich"
        #endif // WOG
        }
    }
}
